### ISSUE TITLE
Cannot connect to host api.capmonster.cloud:443 ssl:True

### ISSUE THREAD

**Issue by thanhansoft** [ZennoLab/capmonstercloud-client-python#26]
Hi bro,

I use sample code and change APIKEY my account has over 2usd but error:
`from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.capmonster.cloud:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_
FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]`

this is code:
`
import asyncio

from capmonstercloudclient import CapMonsterClient, ClientOptions
from capmonstercloudclient.requests import RecaptchaV2ProxylessRequest

client_options = ClientOptions(api_key='KEY')
cap_monster_client = CapMonsterClient(options=client_options)

async def solve_captcha():
    return await cap_monster_client.solve_captcha(recaptcha2request)

recaptcha2request = RecaptchaV2ProxylessRequest(websiteUrl="https://lessons.zennolab.com/captchas/recaptcha/v2_simple.php?level=high",
                                                websiteKey="6Lcg7CMUAAAAANphynKgn9YAgA4tQ2KI_iqRyTwd")

responses = asyncio.run(solve_captcha())
print(responses)
`

Please help me

**Comment by thanhansoft** [comment]
I'm using window 10, Python 3.10.5 and I have tried many times since yesterday. I have contacted capmonster.cloud team but no response yet.

previously i used python api code below, but since 12-11 it is broken, so i have to check latest documentation from https://docs.capmonster.cloud/docs/getting-start/ and got the above problem.

here is the old code that did not run 2 days ago:

`API_KEY = 'my_key' 
WEBSITE_KEY = "6Lcg7CMUAAAAANphynKgn9YAgA4tQ2KI_iqRyTwd"

async def solve_captcha(api_key, website_url, website_key):
    client_options = ClientOptions(api_key=api_key)
    cap_monster_client = CapMonsterClient(options=client_options)
    recaptcha_request = RecaptchaV2ProxylessRequest(websiteUrl=website_url, websiteKey=website_key)
    return await cap_monster_client.solve_captcha(recaptcha_request)

def get_captcha_solution(api_key, website_url, website_key):
    try:
        result = asyncio.run(solve_captcha(api_key, website_url, website_key))
        print(result)
        return result['gRecaptchaResponse']
    except Exception as e:
        return str(e)
   
def main():
    captcha_result = get_captcha_solution(API_KEY, "https://lessons.zennolab.com/captchas/recaptcha/v2_simple.php?level=high", WEBSITE_KEY)

main()`

**Comment by grk717** [comment]
can you try following on a clean environment?
```
python -m pip install --upgrade pip
pip install --upgrade certifi
pip install capmonstercloudclient
```
seems to be the problem with local certificates

**Comment by thanhansoft** [comment]
After running your 3 commands another error appears:

> E:\Python\test>python main.py
C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_model_construction.py:61: UserWarning: `validate_urls_array` overrides an existing Pydantic `@validator` decorator
  warnings.warn(f'`{k}` overrides an existing Pydantic `{existing.decorator_info.decorator_repr}` decorator')
Traceback (most recent call last):
  File "E:\Python\test\main.py", line 15, in <module>
    responses = asyncio.run(solve_captcha())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Python\test\main.py", line 10, in solve_captcha
    return await cap_monster_client.solve_captcha(recaptcha2request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\site-packages\capmonstercloudclient\CapMonsterCloudClient.py", line 90, in solve_captcha
    return await self._solve(request, get_timeouts())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\site-packages\capmonstercloudclient\CapMonsterCloudClient.py", line 115, in _solve
    getTaskResponse = await self._createTask(request)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\site-packages\capmonstercloudclient\CapMonsterCloudClient.py", line 172, in _createTask
    async with session.post(url=self.options.service_url + '/createTask',
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 1359, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client.py", line 688, in _request
    resp = await req.send(conn)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\client_reqrep.py", line 775, in send
    await writer.write_headers(status_line, self.headers)
  File "C:\Users\Thanhansoft\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiohttp\http_writer.py", line 130, in write_headers
    buf = _serialize_headers(status_line, headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp\\_http_writer.pyx", line 116, in aiohttp._http_writer._safe_header
ValueError: Newline or carriage return character detected in HTTP status message or header. This is a potential security issue.

![Screenshot_124](https://github.com/user-attachments/assets/4d23e4ab-3ca1-440f-a8bc-2e7df96544b0)

**Comment by grk717** [comment]
That was the problem in 1.5.1 version of capmonstercloudclient, it's fixed in 1.5.2.
Or, you can go to your installed lib path and delete newline at version.txt file.

**Comment by thanhansoft** [comment]
Hi,

I still get error 443 even though I upgraded successfully to 1.5.2

`Error: Cannot connect to host api.capmonster.cloud:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]
Error occurred: 'NoneType' object is not subscriptable`

> C:\Users\XEON\Desktop\infocom>pip show capmonstercloudclient
Name: capmonstercloudclient
Version: 1.5.2
Summary: Official CapMonsterCloud Client: https://capmonster.cloud/
Home-page: https://github.com/ZennoLab/capmonstercloud-client-python
Author: Andrey Ilyin
Author-email: andrey.ilyin@zennolab.com
License: AGPL-3.0
Location: C:\Users\XEON\AppData\Roaming\Python\Python312\site-packages
Requires: aiohttp, pydantic
Required-by:

**Comment by thanhansoft** [comment]
`C:\Users\XEON>pip show certifi
Name: certifi
Version: 2024.8.30
Summary: Python package for providing Mozilla's CA Bundle.
Home-page: https://github.com/certifi/python-certifi
Author: Kenneth Reitz
Author-email: me@kennethreitz.com
License: MPL-2.0
Location: C:\Users\XEON\AppData\Roaming\Python\Python312\site-packages
Requires:
Required-by: requests, selenium`

**Comment by grk717** [comment]
Unfortunately, I couldn't reproduce this problem on three different environments, but some of our users also experience the same problem. Here's couple suggestions you may try:

1. Use new conda environment (install conda for windows, run
 ```
conda create -n test_env python=3.10
conda activate test_env
pip install capmonstercloudclient
python your_script.py
```
While creating environment, conda will pull ca-certificates-2024.9.24 bundle.
2. Import certificate from capmonstercloud to your system, like described here: https://github.com/aio-libs/aiohttp/issues/955#issuecomment-2024062890
You may use https://api.capmonster.cloud/createTask link in chrome to reach for certificate.

**Comment by thanhansoft** [comment]
Is there any other way? too much trouble, my program has been stopped for days now
